login_info:
  school_name: # 学校名称
  username: # 用户名
  password: # 密码
  retry_times: 5 # 登录重试次数

captcha: # 自动打码
  enable: false
  pd_id: # 请前往 http://www.fateadm.com 获取
  pd_key: # 请前往 http://www.fateadm.com 获取

noticer: # Server酱推送
  enable: false
  secret_key: # Server酱密钥，请前往 http://sc.ftqq.com/ 注册并绑定微信后获取

cron: 0 0 9 * * * # 计划任务规则
log_level: info # 日志级别 debug/info/warning/error